# FOSRestBundle Configuration
fos_rest:
    format_listener:
        rules:
            - prefer_extension: false
    view:
        view_response_listener: true
        formats:
            json: true
            xml: true
