services:
    # Services
    wade_core.service.stardog:
        class: WADE\CoreBundle\Service\StardogService
        arguments:
            - "@service_container"
            - "%stardog_user%"
            - "%stardog_password%"
            - "%stardog_host%"
            - "%stardog_port%"
            - "%stardog_database_name%"

    wade_core.service.dbpedia:
        class: WADE\CoreBundle\Service\DbpediaService
        arguments:
            - "@service_container"
            - "%dbpedia_endpoint%"

    # Managers
    wade_core.manager.phobia_manager:
        class: WADE\CoreBundle\Manager\PhobiaManager
        arguments:
            - "@service_container"
            - "@wade_core.service.stardog"

    wade_core.manager.user_manager:
        class: WADE\CoreBundle\Manager\UserManager
        arguments:
            - "@service_container"
            - "@wade_core.service.stardog"
